export const en = {
  chooseLanguage: "Choose your language",
  continue: "Continue",
  appName: "Bhumisutra",
  tagline: "Groundwater-aware crop advice for your farm",
  yourLocation: "Your Location",
  state: "State",
  district: "District",
  area: "Area",
  detecting: "Detecting your location...",
  weather: "Weather",
  temperature: "Temperature",
  humidity: "Humidity",
  rainfall: "Rainfall",
  low: "Low",
  moderate: "Moderate",
  high: "High",
  viewRecommendations: "View Crop Recommendations",
  viewGroundwater: "View Groundwater Status",
  shareSummary: "Share Summary",
  settings: "Settings",
  changeLanguage: "Change Language",
  recommendedCrops: "Recommended Crops",
  bestRecommendation: "Best Recommendation",
  suitabilityScore: "Suitability Score",
  waterDemand: "Water Demand",
  groundwaterRisk: "Groundwater Risk",
  whyThisCrop: "Why this crop?",
  groundwaterStatus: "Groundwater Status",
  currentLevel: "Current groundwater level",
  historicalTrend: "Historical trend (2021-2025)",
  unavailable: "Unavailable",
  depleting: "Depleting",
  stable: "Stable",
  improving: "Improving",
  insufficientData: "Insufficient Data",
  depletingExplain: "Groundwater levels here have been getting deeper in recent years, so crops with lower water demand are preferred.",
  stableExplain: "Groundwater levels here have stayed relatively steady in recent years.",
  improvingExplain: "Groundwater levels here have been rising in recent years, giving more flexibility for water-demanding crops.",
  insufficientExplain: "Not enough historical data was found for this exact area to determine a trend.",
  locationPermissionDenied: "Location permission was denied. Please select your location manually.",
  locationUnavailable: "We couldn't detect your location automatically. Please choose it manually.",
  weatherUnavailable: "Live weather couldn't be fetched. Please enter it manually.",
  selectManually: "Select Manually",
  retry: "Try Again",
  enterManually: "Enter Manually",
  save: "Save",
  loadingRecommendations: "Calculating crop recommendations...",
  methodology: "About / Methodology",
  shareTitle: "Shareable Summary",
  shareDescription: "Share this recommendation with extension workers or your farmer group.",
  share: "Share",
  groupName: "Farmer / Group Name (optional)",
  reason_N_GOOD: "Good match for soil nitrogen levels",
  reason_P_GOOD: "Good match for soil phosphorus levels",
  reason_K_GOOD: "Good match for soil potassium levels",
  reason_TEMP_GOOD: "Well suited to current temperature",
  reason_HUMIDITY_GOOD: "Well suited to current humidity",
  reason_RAINFALL_GOOD: "Well suited to current rainfall",
  reason_LOW_WATER_ADVANTAGE: "Low water requirement - easier on groundwater",
  reason_HIGH_WATER_CAUTION: "Higher water requirement than most crops",
  reason_GW_DEPLETING_CAUTION: "Groundwater is depleting in your area - water-saving crops are favoured",
  reason_GW_IMPROVING_ADVANTAGE: "Groundwater is improving in your area, giving more crop flexibility",
  dataEstimatedNote: "Water demand estimated from standard reference data (not from your local dataset)",
  npkStateAverageNote: "Exact district soil data not found - using state average instead",
};