export const hi = {
  chooseLanguage: "अपनी भाषा चुनें",
  continue: "जारी रखें",
  appName: "भूमिसूत्र",
  tagline: "आपके खेत के लिए भूजल-अनुकूल फसल सलाह",
  yourLocation: "आपका स्थान",
  state: "राज्य",
  district: "जिला",
  area: "क्षेत्र",
  detecting: "आपका स्थान पता लगाया जा रहा है...",
  weather: "मौसम",
  temperature: "तापमान",
  humidity: "नमी",
  rainfall: "वर्षा",
  low: "कम",
  moderate: "मध्यम",
  high: "अधिक",
  viewRecommendations: "फसल सिफारिशें देखें",
  viewGroundwater: "भूजल स्थिति देखें",
  shareSummary: "सारांश साझा करें",
  settings: "सेटिंग्स",
  changeLanguage: "भाषा बदलें",
  recommendedCrops: "अनुशंसित फसलें",
  bestRecommendation: "सर्वश्रेष्ठ सिफारिश",
  suitabilityScore: "उपयुक्तता स्कोर",
  waterDemand: "पानी की आवश्यकता",
  groundwaterRisk: "भूजल जोखिम",
  whyThisCrop: "यह फसल क्यों?",
  groundwaterStatus: "भूजल स्थिति",
  currentLevel: "वर्तमान भूजल स्तर",
  historicalTrend: "ऐतिहासिक रुझान (2021-2025)",
  unavailable: "उपलब्ध नहीं",
  depleting: "घट रहा है",
  stable: "स्थिर",
  improving: "सुधर रहा है",
  insufficientData: "अपर्याप्त डेटा",
  depletingExplain: "हाल के वर्षों में इस क्षेत्र में भूजल स्तर गहरा होता जा रहा है, इसलिए कम पानी की आवश्यकता वाली फसलें बेहतर हैं।",
  stableExplain: "हाल के वर्षों में इस क्षेत्र में भूजल स्तर अपेक्षाकृत स्थिर रहा है।",
  improvingExplain: "हाल के वर्षों में इस क्षेत्र में भूजल स्तर बढ़ रहा है, जिससे अधिक पानी वाली फसलों के लिए भी गुंजाइश बनती है।",
  insufficientExplain: "इस क्षेत्र के लिए रुझान तय करने हेतु पर्याप्त ऐतिहासिक डेटा नहीं मिला।",
  locationPermissionDenied: "स्थान की अनुमति अस्वीकृत की गई। कृपया अपना स्थान मैन्युअल रूप से चुनें।",
  locationUnavailable: "हम आपका स्थान स्वचालित रूप से पता नहीं लगा सके। कृपया मैन्युअल रूप से चुनें।",
  weatherUnavailable: "लाइव मौसम प्राप्त नहीं हो सका। कृपया मैन्युअल रूप से दर्ज करें।",
  selectManually: "मैन्युअल रूप से चुनें",
  retry: "पुनः प्रयास करें",
  enterManually: "मैन्युअल रूप से दर्ज करें",
  save: "सहेजें",
  loadingRecommendations: "फसल सिफारिशों की गणना हो रही है...",
  methodology: "जानकारी / पद्धति",
  shareTitle: "साझा करने योग्य सारांश",
  shareDescription: "इस सिफारिश को विस्तार कार्यकर्ताओं या अपने किसान समूह के साथ साझा करें।",
  share: "साझा करें",
  groupName: "किसान / समूह का नाम (वैकल्पिक)",
  reason_N_GOOD: "मिट्टी में नाइट्रोजन स्तर के लिए अच्छा मेल",
  reason_P_GOOD: "मिट्टी में फॉस्फोरस स्तर के लिए अच्छा मेल",
  reason_K_GOOD: "मिट्टी में पोटेशियम स्तर के लिए अच्छा मेल",
  reason_TEMP_GOOD: "वर्तमान तापमान के लिए उपयुक्त",
  reason_HUMIDITY_GOOD: "वर्तमान नमी के लिए उपयुक्त",
  reason_RAINFALL_GOOD: "वर्तमान वर्षा के लिए उपयुक्त",
  reason_LOW_WATER_ADVANTAGE: "कम पानी की आवश्यकता - भूजल पर कम दबाव",
  reason_HIGH_WATER_CAUTION: "अधिकांश फसलों की तुलना में अधिक पानी की आवश्यकता",
  reason_GW_DEPLETING_CAUTION: "आपके क्षेत्र में भूजल घट रहा है - पानी बचाने वाली फसलों को प्राथमिकता",
  reason_GW_IMPROVING_ADVANTAGE: "आपके क्षेत्र में भूजल सुधर रहा है, जिससे अधिक फसल विकल्प मिलते हैं",
  dataEstimatedNote: "पानी की आवश्यकता मानक संदर्भ डेटा से अनुमानित (आपके स्थानीय डेटासेट से नहीं)",
  npkStateAverageNote: "सटीक जिला मिट्टी डेटा नहीं मिला - राज्य औसत का उपयोग किया जा रहा है",
};